Dockerfile: Update ubuntu base
krallin/tini pull request #194
Opened 2022-01-06 13:07 UTC by mrueg

Updated ubuntu base image used to build from 16.04 to 20.04 as 16.04 is out of (unpaid) support

2022-04-28 15:43 UTC, AkihiroSuda commented on Dockerfile
> +FROM ubuntu:20.04
Now there is 22.04

2022-06-28 02:35 UTC, onedr0p requested changes

2022-06-28 02:35 UTC, onedr0p commented on Dockerfile
> +FROM ubuntu:20.04
```suggestion
FROM ubuntu:22.04
```

2024-06-02 15:54 UTC, mrueg commented
Repository owner doesn't seem to be interested in this change.

2024-06-02 15:54 UTC, closed without merging

2024-06-02 16:11 UTC, onedr0p commented
I've switched to https://github.com/openSUSE/catatonit 
Pretty much the same thing but looks more active.